name: Formatter

on:
    push:
        branches: [master]
        paths:
            - "assets/css/**"
            - "assets/js/**"
            - ".github/workflows/formatter.yml"

jobs:
    Prettier:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout project
              uses: actions/checkout@v3

            - name: Format ${{ matrix.language }} files
              uses: creyD/prettier_action@v4.2
              with:
                  prettier_options: --write assets/css/*.{json,css,scss} assets/js/**/*.js
                  same_commit: false
                  commit_message: "[CI] Format Code!"
                  commit_description: "Format code using Prettier"
