name: Formatter

on: [push]

jobs:
    prettier:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - language: CSS
                      path: "css"
                      extension: "css"
                    - language: Sass
                      path: "css"
                      extension: "scss"
                    - language: Javascript
                      path: "js"
                      extension: "js"

        steps:
            - name: Checkout project
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0

            - name: Format ${{ matrix.language }} codes
              uses: creyD/prettier_action@v4.2
              with:
                  prettier_options: --write assets/${{ matrix.path }}/**/*.${{ matrix.extension }}
                  same_commit: false
                  commit_message: "[CI] Format Code!"
                  commit_description: "Format code using Prettier"
