name: Formatter

on:
    push:
        branches: [master]
        paths:
            - "assets/css/**"
            - "assets/js/**"
            - ".github/workflows/formatter.yml"

env:
    REF: ""

jobs:
    Prettier:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 1
            fail-fast: false
            matrix:
                include:
                    - language: CSS
                      path: "assets/css/"
                      extension: "css"
                    - language: Sass
                      path: "assets/css/"
                      extension: "scss"
                    - language: Javascript
                      path: "assets/js/"
                      extension: "js"
                    - language: JSON
                      path: ""
                      extension: "json"

        steps:
            - name: Checkout project
              uses: actions/checkout@v3
              with:
                  ref: ${{ env.REF }}

            - name: Format ${{ matrix.language }} files
              uses: creyD/prettier_action@v4.2
              with:
                  prettier_options: --write ${{ matrix.path }}**/*.${{ matrix.extension }}
                  same_commit: false
                  commit_message: "[CI] Format Code!"
                  commit_description: "Format code using Prettier"

            - name: Set REF
              run: |
                  git log -1 --format='%H'
                  echo "REF=$(git log -1 --format='%H')" >> $GITHUB_ENV
