name: ✅ Tests

on:
    push:
        branches: [master]

jobs:
    build:
        name: ✅ Test
        runs-on: ubuntu-latest

        steps:
            - name: ⬇️ Checkout project
              uses: actions/checkout@v6

            - name: 📥 Install NodeJS
              uses: actions/setup-node@v6
              with:
                  node-version: 22.22.1

            - name: 📥 Install dependencies
              run: yarn install

            - name: 🔎 Test
              run: yarn test:ci

            - name: 🔎 Pre-Test
              run: yarn pretest
